-- Create these three disconnected tables with Modeling > New table.

ScenarioLeadTime =
GENERATESERIES(7, 28, 1)

ScenarioReviewPeriod =
DATATABLE(
    "Days", INTEGER,
    {
        {0}, {7}, {14}, {21}, {28}
    }
)

ScenarioServiceLevel =
DATATABLE(
    "Scenario", STRING,
    "Z", DOUBLE,
    {
        {"ABC default", BLANK()},
        {"85%", 1.0364333894937898},
        {"90%", 1.2815515655446004},
        {"95%", 1.6448536269514722},
        {"97%", 1.8807936081512509},
        {"99%", 2.3263478740408408}
    }
)
